### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by dbpolito** [fireworkweb/docker-http#2]
### TODOs

- [x] 1. Remove https://github.com/fireworkweb/docker-http/blob/master/Dockerfile#L5-L6, already on built image: https://github.com/nginxinc/docker-nginx/blob/baa050df601b5e798431a9db458e16f53b1031f6/mainline/alpine/Dockerfile#L136-L137
- [x] 2. Do we really need https://github.com/fireworkweb/docker-http/blob/master/Dockerfile#L8 for dev? This isn't added by default at forge. We don't always use that. 
- [ ] 3. Write README with meaningful explanation
